// generated by: generate_version_info.sh "1.13.0" "a.denisov@corp.badoo.com" "" "/Library/Developer/CommandLineTools/usr/bin/make - " 
// DO NOT EDIT!

package main

import (
	"badoo/_packages/service"
	"badoo/_packages/service/stats"
	"github.com/gogo/protobuf/proto"
)

func init() {
	service.VersionInfo = badoo_service.ResponseVersion{
		Version:        proto.String("1.13.0"),
		AutoBuildTag:   proto.String(""),
		BuildDate:      proto.String("Tue Nov 14 17:03:20 UTC 2017"),
		BuildHost:      proto.String("mbp-adenisov"),
		BuildCc:        proto.String("go version go1.8.3 darwin/amd64"),
		BuildConfigure: proto.String("/Library/Developer/CommandLineTools/usr/bin/make - "),
		VcsType:        proto.String("git"),
		VcsBasename:    proto.String("lsd"),
		VcsNum:         proto.String("9"),
		VcsDate:        proto.String("2017-05-10T14:34:55+0300"),
		VcsBranch:      proto.String("master"),
		VcsTag:         proto.String(""),
		VcsTick:        proto.String("9"),
		VcsFullHash:    proto.String("982ee6eb623494c037f08cc392de11701609ea9a"),
		VcsShortHash:   proto.String("982ee6e"),
		VcsWcModified:  proto.String("1"),
		Maintainer:     proto.String("a.denisov@corp.badoo.com"),
	}
}
